bot {
    token = ${?BOT_TOKEN}
}

db {
    host = ${?DB_HOST}
    name = ${?DB_NAME}
    jdbcUrl = "jdbc:postgresql://"${db.host}":5432/"${db.name}"?sslmode=disable"
    username = ${?DB_USERNAME}
    password = ${?DB_PASSWORD}
    driverClassName = "org.postgresql.Driver"
    maximumPoolSize = 10
}
